import type { EditorThemeClasses } from "lexical"

export const editorTheme: EditorThemeClasses = {
  paragraph: "yaba-editor-paragraph",
  heading: {
    h1: "yaba-editor-h1",
    h2: "yaba-editor-h2",
    h3: "yaba-editor-h3",
    h4: "yaba-editor-h4",
    h5: "yaba-editor-h5",
    h6: "yaba-editor-h6",
  },
  list: {
    ul: "yaba-editor-ul",
    ol: "yaba-editor-ol",
    listitem: "yaba-editor-li",
  },
  link: "yaba-editor-link",
  text: {
    bold: "yaba-editor-bold",
    italic: "yaba-editor-italic",
    underline: "yaba-editor-underline",
    strikethrough: "yaba-editor-strikethrough",
    code: "yaba-editor-code",
  },
  quote: "yaba-editor-quote",
  code: "yaba-editor-code-block",
  codeHighlight: {
    atrule: "yaba-editor-code-atrule",
    attr: "yaba-editor-code-attr",
    boolean: "yaba-editor-code-boolean",
    builtin: "yaba-editor-code-builtin",
    cdata: "yaba-editor-code-cdata",
    char: "yaba-editor-code-char",
    class: "yaba-editor-code-class",
    "class-name": "yaba-editor-code-class-name",
    comment: "yaba-editor-code-comment",
    constant: "yaba-editor-code-constant",
    deleted: "yaba-editor-code-deleted",
    doctype: "yaba-editor-code-doctype",
    entity: "yaba-editor-code-entity",
    function: "yaba-editor-code-function",
    important: "yaba-editor-code-important",
    inserted: "yaba-editor-code-inserted",
    keyword: "yaba-editor-code-keyword",
    namespace: "yaba-editor-code-namespace",
    number: "yaba-editor-code-number",
    operator: "yaba-editor-code-operator",
    prolog: "yaba-editor-code-prolog",
    property: "yaba-editor-code-property",
    punctuation: "yaba-editor-code-punctuation",
    regex: "yaba-editor-code-regex",
    selector: "yaba-editor-code-selector",
    string: "yaba-editor-code-string",
    symbol: "yaba-editor-code-symbol",
    tag: "yaba-editor-code-tag",
    url: "yaba-editor-code-url",
    variable: "yaba-editor-code-variable",
  },
  table: "yaba-editor-table",
  tableCell: "yaba-editor-table-cell",
  tableCellHeader: "yaba-editor-table-cell-header",
  tableRow: "yaba-editor-table-row",
  horizontalRule: "yaba-editor-hr",
}
